export const SIZES = {
  MID_BLOCK: 16,
  BLOCK: 32,
  DOUBLE_BLOCK: 64,
  THREE_BLOCKS: 96,
  FOUR_BLOCKS: 128
};

export const DEPTH = {
  BACKGROUND: 0,
  GROUND: 10,
  DOOR_SPRITES: 15,
  ON_THE_FLY_OBJECTS: 19,
  PLAYER: 20,
  CITIZENS: 20,
  FLOOR_ANIMALS: 19,
  ON_THE_FLY_OBJECTS_ABOVE_PLAYER: 30,
  FLYING_ANIMALS: 31,
  UI: 40,
  PLAYER_OVER_EVERYTHING_ELSE: 39,
  LIGHTS: 50
};
